<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.25" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="AspNetCore.HealthChecks.Sqlite" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<!-- JWT 认证 -->
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.1" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Mud.Feishu.Abstractions" Version="3.0.0-preview3" />
		<PackageReference Include="Mud.Feishu" Version="3.0.0-preview3" />
		<PackageReference Include="Mud.Feishu.Authentication" Version="3.0.0-preview3" />
		<PackageReference Include="Mud.Feishu.Webhook" Version="3.0.0-preview3" />
		<PackageReference Include="Mud.Feishu.EventCallback" Version="3.0.0-preview3" />
	</ItemGroup>
	<!-- <ItemGroup>
		<ProjectReference Include="..\..\..\Mud.Feishu\Mud.Feishu.csproj" />
		<ProjectReference Include="..\..\..\Mud.Feishu.Webhook\Mud.Feishu.Webhook.csproj" />
		<ProjectReference Include="..\..\..\Mud.Feishu.Authentication\Mud.Feishu.Authentication.csproj" />
		<ProjectReference Include="..\..\..\Mud.Feishu.EventCallback\Mud.Feishu.EventCallback.csproj" />
	</ItemGroup> -->
</Project>
