<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>FeishuFileServer</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <None Include="appsettings.local.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.25" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.25" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.25" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.25" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Mud.Feishu" Version="2.1.0" />
		<PackageReference Include="Mud.Feishu.Authentication" Version="2.1.0" />
	</ItemGroup>
    <!--<ItemGroup>
		<ProjectReference Include="..\..\..\Mud.Feishu.Authentication\Mud.Feishu.Authentication.csproj" />
		<ProjectReference Include="..\..\..\Mud.Feishu\Mud.Feishu.csproj" />
    </ItemGroup>-->

    <ItemGroup>
        <Content Update="appsettings.local.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
