<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mud.Feishu.Abstractions" Version="3.0.0-preview3" />
    <PackageReference Include="Mud.Feishu.Webhook" Version="3.0.0-preview3" />
    <PackageReference Include="Mud.Feishu.EventCallback" Version="3.0.0-preview3" />
  </ItemGroup>

  <!--<ItemGroup>
    <ProjectReference Include="..\..\Mud.Feishu.Webhook\Mud.Feishu.Webhook.csproj" />
	<ProjectReference Include="..\..\Mud.Feishu.EventCallback\Mud.Feishu.EventCallback.csproj" />
  </ItemGroup>-->
</Project>
