<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mud.Feishu.Abstractions\Mud.Feishu.Abstractions.csproj" />
    <ProjectReference Include="..\..\Mud.Feishu\Mud.Feishu.csproj" />
    <ProjectReference Include="..\..\Mud.Feishu.Authentication\Mud.Feishu.Authentication.csproj" />
    <ProjectReference Include="..\..\Mud.Feishu.EventCallback\Mud.Feishu.EventCallback.csproj" />
  </ItemGroup>

</Project>
