<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Mud.Feishu.Demo</RootNamespace>
	</PropertyGroup>
	<!-- <ItemGroup>
	  <PackageReference Include="Mud.Feishu" Version="2.0.9" />
	  <PackageReference Include="Mud.Feishu.Authentication" Version="2.0.9" />
	</ItemGroup> -->
	<ItemGroup>
		<ProjectReference Include="..\..\Mud.Feishu.Authentication\Mud.Feishu.Authentication.csproj" />
		<ProjectReference Include="..\..\Mud.Feishu\Mud.Feishu.csproj" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0' or '$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<DefineConstants>net8</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<DefineConstants>net9</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<DefineConstants>net10</DefineConstants>
	</PropertyGroup>
</Project>