<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net6.0;net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>Mud.Feishu.Webhook</AssemblyName>
		<InterceptorsPreviewNamespaces>true</InterceptorsPreviewNamespaces>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<PackageProjectUrl>http://www.mudtools.cn/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/mudtools/MudFeishu</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageIcon>Icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>适用于 .NET 全平台的飞书 Webhook 事件订阅组件，提供开箱即用的客户端实现，基于策略模式构建可扩展的事件处理机制，帮助开发者在 .NET 应用中便捷、可靠地接收和处理飞书实时事件。</Description>
		<PackageTags>Feishu;Lark;飞书;ByteDance;字节跳动;Feishu-SDK;Lark-SDK;Feishu-Webhook;Lark-Webhook;Webhook;HTTP-Callback;回调;Event-Subscription;事件订阅;Signature-Verification;签名验证;MudFeishu</PackageTags>
		<BaseOutputPath>..\bin</BaseOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<CompilerVisibleProperty Include="JsonSerializerIsReflectionEnabledByDefault" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="Mud.Feishu.Webhook.Tests" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0' or '$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
		<!-- <PackageReference Include="Mud.Feishu.Abstractions" Version="1.1.2" /> -->
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Mud.Feishu.Abstractions\Mud.Feishu.Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include=".\README.md" Pack="true" PackagePath="\" />
		<None Include="..\Icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
