// -----------------------------------------------------------------------
//  作者：Mud Studio  版权所有 (c) Mud Studio 2026
//  Mud.Feishu 项目的版权、商标、专利和其他相关权利均受相应法律法规的保护。使用本项目应遵守相关法律法规和许可证的要求。
//  本项目主要遵循 MIT 许可证进行分发和使用。许可证位于源代码树根目录中的 LICENSE-MIT 文件。
//  不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目开发而产生的一切法律纠纷和责任，我们不承担任何责任！
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Mud.Feishu.AI.Tools.Extraction;
using Mud.Feishu.AI.Tools.Schema;

namespace Mud.Feishu.AI.Tools.Emit;

/// <summary>
/// Tier R 能力目录发射器（<b>可选</b>，由 <c>build_property.FeishuToolCatalog=true</c> 开启）：
/// 遍历 <c>Mud.Feishu</c> 程序集的全部 SDK 接口，产出<b>聚合</b>能力目录。
/// </summary>
/// <remarks>
/// <para>
/// <b>为什么不逐方法发射</b>（本方案评审的纠正点）：可行性研究阶段的设计（AT-F01）计划"为每条
/// 能力发射直调执行器"，但执行器承载的是<b>有意的策展</b>——哪些字段回填模型、JSON 键怎么命名、
/// 错误如何归类——这恰恰是护城河（白名单投影），生成器无从得知。逐方法发射 1155 条 Schema
/// 还会把编译期成本与程序集体积推高一个量级。故 Tier R 只交付<b>可度量的目录事实</b>：
/// SDK 能力总量、模块分布、策展覆盖率——使"能力面差距"从主观判断变成构建期可见的数字。
/// </para>
/// <para>
/// <b>粒度纪律</b>：枚举只统计各接口<b>自身声明</b>的方法（<c>GetMembers()</c>，不含
/// <c>AllInterfaces</c>）——本仓库的方法声明在基接口 <c>IFeishuV*</c> 上，若把继承也算进来，
/// 同一方法会被每个派生接口重复计数。
/// </para>
/// </remarks>
internal static class CapabilityCatalogEmitter
{
    /// <summary>扫描 SDK 程序集并产出能力目录源；未引用 <c>Mud.Feishu</c> 时静默跳过。</summary>
    public static void Emit(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<ToolSchemaModel> curatedModels)
    {
        var feishu = compilation.SourceModule.ReferencedAssemblySymbols
            .FirstOrDefault(static a => string.Equals(a.Name, "Mud.Feishu", StringComparison.Ordinal));
        if (feishu is null)
        {
            return;
        }

        var methodsByModule = new SortedDictionary<string, int>(StringComparer.Ordinal);
        var totalMethods = 0;
        var unnamedInterfaces = 0;

        foreach (var type in EnumerateInterfaces(feishu.GlobalNamespace))
        {
            var declared = type.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(static m => m.MethodKind == MethodKind.Ordinary && m.DeclaredAccessibility == Accessibility.Public)
                .ToArray();
            if (declared.Length == 0)
            {
                continue;
            }

            totalMethods += declared.Length;

            var module = "Unparsed";
            if (Extractors.TryParseSdkInterfaceName(type.Name, out _, out var domain, out _))
            {
                module = domain;
            }
            else
            {
                unnamedInterfaces++;
            }

            methodsByModule[module] = methodsByModule.TryGetValue(module, out var count)
                ? count + declared.Length
                : declared.Length;
        }

        var coverage = DescriptorValidator.ComputeCoverage(curatedModels.Select(static m => m.Entry), totalMethods);

        EmitSource(context, methodsByModule, totalMethods, coverage);

        // MUDFT018 上报点：聚合单条（避免逐方法刷屏）。
        Diagnostics.Report(
            context,
            Diagnostics.MUDFT018,
            null,
            totalMethods,
            coverage.ToolCount,
            coverage.ToolCoverageRate.ToString("P1", System.Globalization.CultureInfo.InvariantCulture),
            methodsByModule.Count);
    }

    private static void EmitSource(
        SourceProductionContext context,
        SortedDictionary<string, int> methodsByModule,
        int totalMethods,
        CoverageReport coverage)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated> 由 FeishuToolSchemaGenerator 编译期产出，禁止手工修改 </auto-generated>");
        source.AppendLine("#nullable enable");
        source.AppendLine("#pragma warning disable CS1591 // 生成代码不逐一补 XML 注释");
        source.AppendLine("namespace Mud.Feishu.AI.Tools.Generated");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>SDK 能力目录快照（聚合事实；未暴露单元的具体方法名不进产物）。</summary>");
        source.AppendLine($"    {GeneratedCodeMarker.Attribute}");
        source.AppendLine("    internal static class FeishuCapabilityCatalog");
        source.AppendLine("    {");
        source.AppendLine("        /// <summary>SDK 接口声明的方法总数。</summary>");
        source.AppendLine($"        public const int SdkMethodCount = {totalMethods};");
        source.AppendLine("        /// <summary>已策展（对外暴露）的工具数。</summary>");
        source.AppendLine($"        public const int CuratedToolCount = {coverage.ToolCount};");
        source.AppendLine("        /// <summary>");
        source.AppendLine("        /// 输出契约完整的工具数（声明了非空 output_schema 且推导未被截断）。");
        source.AppendLine("        /// </summary>");
        source.AppendLine("        /// <remarks>");
        source.AppendLine("        /// R2-05：这是 <c>CoverageReport.OutputSchemaRate</c> 的<b>分子</b>（分母 = CuratedToolCount）——");
        source.AppendLine("        /// 该度量在 R5 之前恒为 1.0、R5 之后恒为 0，两次都是假值；此处是它的第一个真实消费点");
        source.AppendLine("        /// （契约守卫断言 OutputSchemaCoveredToolCount ≤ CuratedToolCount，且与 golden 快照的 output_schema 面一致）。");
        source.AppendLine("        /// 单列分子/分母而<b>不</b>发射浮点率：整数是精确的、跨区域性无关的，且可由消费者自行求商。");
        source.AppendLine("        /// </remarks>");
        source.AppendLine($"        public const int OutputSchemaCoveredToolCount = {coverage.OutputSchemaCoveredToolCount};");
        source.AppendLine("        /// <summary>覆盖的能力分组个数（分组轴 = 接口名的 domain+resource 段，如 BitableAppTable / ApprovalTask）。</summary>");
        source.AppendLine($"        public const int DomainCount = {methodsByModule.Count};");
        source.AppendLine();
        source.AppendLine("        /// <summary>按能力分组统计的方法数（分组轴 = 接口名的 domain+resource 段）。</summary>");
        source.AppendLine($"        {GeneratedCodeMarker.Attribute}");
        source.AppendLine("        public static System.Collections.Generic.IReadOnlyDictionary<string, int> MethodsByDomain { get; } =");
        source.AppendLine("            new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
        source.AppendLine("            {");
        foreach (var pair in methodsByModule)
        {
            source.AppendLine($"                [{JsonText.ToCSharpLiteral(pair.Key)}] = {pair.Value},");
        }

        source.AppendLine("            };");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource("FeishuCapabilityCatalog.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateInterfaces(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            if (type.TypeKind == TypeKind.Interface
                && type.DeclaredAccessibility == Accessibility.Public
                && type.Name.StartsWith("IFeishu", StringComparison.Ordinal))
            {
                yield return type;
            }
        }

        foreach (var child in ns.GetNamespaceMembers())
        {
            foreach (var type in EnumerateInterfaces(child))
            {
                yield return type;
            }
        }
    }
}
