// -----------------------------------------------------------------------
//  作者：Mud Studio  版权所有 (c) Mud Studio 2026
//  Mud.Feishu 项目的版权、商标、专利和其他相关权利均受相应法律法规的保护。使用本项目应遵守相关法律法规和许可证的要求。
//  本项目主要遵循 MIT 许可证进行分发和使用。许可证位于源代码树根目录中的 LICENSE-MIT 文件。
//  不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目开发而产生的一切法律纠纷和责任，我们不承担任何责任！
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Mud.Feishu.AI.Tools.Schema;

namespace Mud.Feishu.AI.Tools.Emit;

/// <summary>
/// 域级 guidance 资产发射器（<b>WP6 / AT-F09</b>）：把 <c>Guidance/{domain}.md</c>（AdditionalFiles）
/// 编译期固化为 <c>FeishuToolGuidance.g.cs</c>。
/// </summary>
/// <remarks>
/// <para>
/// <b>为什么用 AdditionalFiles 而不是源码内 XML 文档（R4.1 评审 R-8）</b>：生成器工程受
/// <c>netstandard2.0</c> 约束，解析 XML doc 注释需要手写解析器（复杂且脆）；AdditionalFiles 的扫描、
/// 读取、比对全部复用既有管线（golden 快照即先例）。
/// </para>
/// <para>
/// <b>与工具面同源</b>：域 guidance 与该域工具同 repo、同一 pass 产出，且装配时只注入
/// <b>已启用工具</b>所属域的 guidance——因此不可能出现"md 说的和工具面不一致"。
/// 发射门槛与 <c>FeishuToolNames</c> / <c>FeishuToolContracts</c> 一致（仅工具面实现包），
/// 否则其他声明 <c>[FeishuTool]</c> 样例接口的工程会多出一个无人消费的静态类。
/// </para>
/// <para>
/// <b>不新增诊断</b>：域 guidance 与工具面的一致性由测试守卫锁定（<c>GuidanceDomainContractGuards</c>）——
/// 新增诊断必须同批补 driver 负例（WP1 的元守卫），而本能力的失败模式（多写一个 md 文件）不值得
/// 引入一条零容忍诊断。
/// </para>
/// </remarks>
internal static class GuidanceEmitter
{
    /// <summary>guidance 资产目录片段（正斜杠归一后匹配：<c>…/Guidance/bitable.md</c>）。</summary>
    public const string FolderSegment = "/Guidance/";

    /// <summary>发射产物文件名。</summary>
    public const string HintName = "FeishuToolGuidance.g.cs";

    /// <summary>判断 AdditionalFile 是否为域 guidance 资产。</summary>
    public static bool IsGuidanceFile(string path)
    {
        var normalized = path.Replace('\\', '/');
        return normalized.EndsWith(".md", StringComparison.OrdinalIgnoreCase)
            && normalized.IndexOf(FolderSegment, StringComparison.OrdinalIgnoreCase) >= 0;
    }

    /// <summary>发射域 guidance 表（无资产或非工具面实现包时静默跳过）。</summary>
    public static void Emit(
        SourceProductionContext context,
        string? assemblyName,
        ImmutableArray<AdditionalText> files,
        System.Threading.CancellationToken cancellationToken)
    {
        if (!string.Equals(assemblyName, SchemaEmitter.ToolNamesOwnerAssembly, StringComparison.Ordinal))
        {
            return;
        }

        // 域 = 文件名去扩展名（如 Guidance/bitable.md → "bitable"）。
        // 用 SortedDictionary 保证产物确定（否则 golden 式的逐字节可比性无从谈起）。
        var blocks = new SortedDictionary<string, string>(StringComparer.Ordinal);
        foreach (var file in files.OrderBy(static f => f.Path, StringComparer.Ordinal))
        {
            var domain = DomainOf(file.Path);
            var text = file.GetText(cancellationToken)?.ToString();
            if (string.IsNullOrWhiteSpace(domain) || string.IsNullOrWhiteSpace(text))
            {
                continue;
            }

            blocks[domain!] = text!.Trim();
        }

        if (blocks.Count == 0)
        {
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated> 由 FeishuToolSchemaGenerator 编译期产出，禁止手工修改 </auto-generated>");
        source.AppendLine("#nullable enable");
        source.AppendLine("#pragma warning disable CS1591 // 生成代码不逐一补 XML 注释");
        source.AppendLine("namespace Mud.Feishu.AI.Tools.Generated");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// 域级 guidance 资产（WP6 / AT-F09）：域 = 工具名首个 '.' 之前的部分；");
        source.AppendLine("    /// 素材为 Guidance/{domain}.md（生成器 AdditionalFiles），内容与该域工具同源同 pass。");
        source.AppendLine("    /// </summary>");
        source.AppendLine($"    {GeneratedCodeMarker.Attribute}");
        source.AppendLine("    public static class FeishuToolGuidance");
        source.AppendLine("    {");
        source.AppendLine("        /// <summary>域 → guidance 正文（装配时只注入已启用工具所属域，见 FeishuGuidanceComposer）。</summary>");
        source.AppendLine($"        {GeneratedCodeMarker.Attribute}");
        source.AppendLine("        public static System.Collections.Generic.IReadOnlyDictionary<string, string> ByDomain { get; } =");
        source.AppendLine("            new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.Ordinal)");
        source.AppendLine("            {");
        foreach (var block in blocks)
        {
            source.AppendLine($"                [{JsonText.ToCSharpLiteral(block.Key)}] = {JsonText.ToCSharpLiteral(block.Value)},");
        }

        source.AppendLine("            };");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(HintName, SourceText.From(source.ToString(), Encoding.UTF8));
    }

    /// <summary>从资产路径取域名（去扩展名的文件名）。</summary>
    private static string? DomainOf(string path)
    {
        var normalized = path.Replace('\\', '/');
        var lastSlash = normalized.LastIndexOf('/');
        var fileName = lastSlash >= 0 ? normalized.Substring(lastSlash + 1) : normalized;
        var dot = fileName.LastIndexOf('.');
        return dot <= 0 ? null : fileName.Substring(0, dot);
    }
}
