// -----------------------------------------------------------------------
//  作者：Mud Studio  版权所有 (c) Mud Studio 2026
//  Mud.Feishu 项目的版权、商标、专利和其他相关权利均受相应法律法规的保护。使用本项目应遵守相关法律法规和许可证的要求。
//  本项目主要遵循 MIT 许可证进行分发和使用。许可证位于源代码树根目录中的 LICENSE-MIT 文件。
//  不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目开发而产生的一切法律纠纷和责任，我们不承担任何责任！
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Mud.Feishu.AI.Tools.Schema;

namespace Mud.Feishu.AI.Tools.Emit;

/// <summary>
/// 域级 guidance 资产发射器（<b>WP6 / AT-F09</b>）：把 <c>Guidance/{domain}.md</c>（AdditionalFiles）
/// 编译期固化为 <c>FeishuToolGuidance.g.cs</c>。
/// </summary>
/// <remarks>
/// <para>
/// <b>为什么用 AdditionalFiles 而不是源码内 XML 文档（R4.1 评审 R-8）</b>：生成器工程受
/// <c>netstandard2.0</c> 约束，解析 XML doc 注释需要手写解析器（复杂且脆）；AdditionalFiles 的扫描、
/// 读取、比对全部复用既有管线（golden 快照即先例）。
/// </para>
/// <para>
/// <b>与工具面同源</b>：域 guidance 与该域工具同 repo、同一 pass 产出，且装配时只注入
/// <b>已启用工具</b>所属域的 guidance——因此不可能出现"md 说的和工具面不一致"。
/// 发射门槛与 <c>FeishuToolNames</c> / <c>FeishuToolContracts</c> 一致（仅工具面实现包），
/// 否则其他声明 <c>[FeishuTool]</c> 样例接口的工程会多出一个无人消费的静态类。
/// </para>
/// <para>
/// <b>不新增诊断</b>：域 guidance 与工具面的一致性由测试守卫锁定（<c>GuidanceDomainContractGuards</c>）——
/// 新增诊断必须同批补 driver 负例（WP1 的元守卫），而本能力的失败模式（多写一个 md 文件）不值得
/// 引入一条零容忍诊断。
/// </para>
/// </remarks>
internal static class GuidanceEmitter
{
    /// <summary>guidance 资产目录片段（正斜杠归一后匹配：<c>…/Guidance/bitable.md</c>）。</summary>
    public const string FolderSegment = "/Guidance/";

    /// <summary>发射产物文件名。</summary>
    public const string HintName = "FeishuToolGuidance.g.cs";

    /// <summary>判断 AdditionalFile 是否为域 guidance 资产。</summary>
    public static bool IsGuidanceFile(string path)
    {
        var normalized = path.Replace('\\', '/');
        return normalized.EndsWith(".md", StringComparison.OrdinalIgnoreCase)
            && normalized.IndexOf(FolderSegment, StringComparison.OrdinalIgnoreCase) >= 0;
    }

    /// <summary>发射域 guidance 表（无资产或非工具面实现包时静默跳过）。</summary>
    public static void Emit(
        SourceProductionContext context,
        string? assemblyName,
        ImmutableArray<AdditionalText> files,
        System.Threading.CancellationToken cancellationToken)
    {
        if (!string.Equals(assemblyName, SchemaEmitter.ToolNamesOwnerAssembly, StringComparison.Ordinal))
        {
            return;
        }

        // L1 = Guidance/{domain}.md（无子目录）；L2 = Guidance/{domain}/{topic}.md（子目录）。
        // 键：L1 用 "{domain}"，L2 用 "{domain}/{topic}"。
        // 用 SortedDictionary 保证产物确定（否则 golden 式的逐字节可比性无从谈起）。
        var blocks = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var references = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var owners = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var file in files.OrderBy(static f => f.Path, StringComparer.Ordinal))
        {
            var key = AssetKeyOf(file.Path);
            var text = file.GetText(cancellationToken)?.ToString();
            if (string.IsNullOrWhiteSpace(key) || string.IsNullOrWhiteSpace(text))
            {
                continue;
            }

            // ⚠️ **冲突必须响亮失败，绝不静默覆盖**（R5 / F-9，评审点②）。
            // 旧实现是 blocks[domain] = text：两个文件映射到同一域时后者直接覆盖前者，
            // **没有任何报错**——而 guidance 是模型的行为依据，覆盖即等于"某域的避坑文本静默消失"。
            // 之所以用抛异常而非新增 MUDFT ID：新增零容忍诊断需同步 Diagnostics /
            // AnalyzerReleases / diagnostics-gate / 三方一致守卫四处；此处抛异常已能让构建失败，
            // 且消息更直接。代价是错误类型不是 MUDFT 编号（登记于 §13 的取舍说明）。
            if (owners.TryGetValue(key!, out var previousOwner))
            {
                throw new InvalidOperationException(
                    $"guidance 资产键冲突：'{key}' 同时由 '{previousOwner}' 与 '{file.Path}' 提供。"
                    + "L1 键为 {domain}（Guidance/{domain}.md），L2 键为 {domain}/{topic}"
                    + "（Guidance/{domain}/{topic}.md）。请重命名其中一份——静默覆盖会让该域的"
                    + "行为依据凭空消失。");
            }

            owners[key!] = file.Path;

            if (key!.Contains('/'))
            {
                references[key] = text!.Trim();
            }
            else
            {
                blocks[key] = text!.Trim();
            }
        }

        if (blocks.Count == 0)
        {
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated> 由 FeishuToolSchemaGenerator 编译期产出，禁止手工修改 </auto-generated>");
        source.AppendLine("#nullable enable");
        source.AppendLine("#pragma warning disable CS1591 // 生成代码不逐一补 XML 注释");
        source.AppendLine("namespace Mud.Feishu.AI.Tools.Generated");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// 域级 guidance 资产（WP6 / AT-F09）：域 = 工具名首个 '.' 之前的部分；");
        source.AppendLine("    /// 素材为 Guidance/{domain}.md（生成器 AdditionalFiles），内容与该域工具同源同 pass。");
        source.AppendLine("    /// </summary>");
        source.AppendLine($"    {GeneratedCodeMarker.Attribute}");
        source.AppendLine("    public static class FeishuToolGuidance");
        source.AppendLine("    {");
        source.AppendLine("        /// <summary>域 → guidance 正文（装配时只注入已启用工具所属域，见 FeishuGuidanceComposer）。</summary>");
        source.AppendLine($"        {GeneratedCodeMarker.Attribute}");
        source.AppendLine("        public static System.Collections.Generic.IReadOnlyDictionary<string, string> ByDomain { get; } =");
        source.AppendLine("            new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.Ordinal)");
        source.AppendLine("            {");
        foreach (var block in blocks)
        {
            source.AppendLine($"                [{JsonText.ToCSharpLiteral(block.Key)}] = {JsonText.ToCSharpLiteral(block.Value)},");
        }

        source.AppendLine("            };");

        // L2：按需读取的深层文本（"feishu.guidance_read" 的唯一数据源）。
        source.AppendLine();
        source.AppendLine("        /// <summary>L2 references：键为 \"{domain}/{topic}\"，供 feishu.guidance_read 按需读取。</summary>");
        source.AppendLine($"        {GeneratedCodeMarker.Attribute}");
        source.AppendLine("        public static System.Collections.Generic.IReadOnlyDictionary<string, string> References { get; } =");
        source.AppendLine("            new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.Ordinal)");
        source.AppendLine("            {");
        foreach (var reference in references)
        {
            source.AppendLine($"                [{JsonText.ToCSharpLiteral(reference.Key)}] = {JsonText.ToCSharpLiteral(reference.Value)},");
        }

        source.AppendLine("            };");
        source.AppendLine();
        source.AppendLine("        /// <summary>可读的 L2 资产清单（形如 \"{domain}/{topic}\"），用于错误提示与守卫。</summary>");
        source.AppendLine($"        {GeneratedCodeMarker.Attribute}");
        source.AppendLine("        public static string[] ReferenceKeys { get; } = new string[]");
        source.AppendLine("        {");
        foreach (var reference in references)
        {
            source.AppendLine($"            {JsonText.ToCSharpLiteral(reference.Key)},");
        }

        source.AppendLine("        };");
        source.AppendLine();
        source.AppendLine("        /// <summary>按键取 L2 文本；不存在返回 false（不抛异常，调用方负责给可执行提示）。</summary>");
        source.AppendLine($"        {GeneratedCodeMarker.Attribute}");
        source.AppendLine("        public static bool TryGetReference(string key, out string text)");
        source.AppendLine("            => References.TryGetValue(key, out text!);");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(HintName, SourceText.From(source.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// 从资产路径取<b>资产键</b>（R5 / F-9）。
    /// </summary>
    /// <remarks>
    /// <para>
    /// 旧实现只取<b>文件名</b>（<c>Guidance/bitable.md</c> → <c>"bitable"</c>），因此一旦引入
    /// 子目录 <c>Guidance/im/replies.md</c>，键会变成 <c>"replies"</c>——与真正的域名混在一起，
    /// 且不同域下的同名 topic 会<b>静默互相覆盖</b>。
    /// </para>
    /// <para>
    /// 现改为：取 <c>Guidance/</c> 之后的相对路径去扩展名 ——
    /// 无子目录 ⇒ L1 键 <c>{domain}</c>（保持既有键不变，向后兼容）；
    /// 有子目录 ⇒ L2 键 <c>{domain}/{topic}</c>。
    /// </para>
    /// </remarks>
    private static string? AssetKeyOf(string path)
    {
        var normalized = path.Replace('\\', '/');
        const string root = "Guidance/";
        var start = normalized.IndexOf(root, StringComparison.OrdinalIgnoreCase);
        var relative = start >= 0
            ? normalized.Substring(start + root.Length)
            : normalized;

        var lastSlash = relative.LastIndexOf('/');
        var tail = lastSlash >= 0 ? relative.Substring(lastSlash + 1) : relative;
        var dot = tail.LastIndexOf('.');
        if (dot <= 0)
        {
            return null;
        }

        var key = relative.Substring(0, dot);
        return key.Length == 0 ? null : key;
    }
}
