// -----------------------------------------------------------------------
//  作者：Mud Studio  版权所有 (c) Mud Studio 2026
//  Mud.Feishu 项目的版权、商标、专利和其他相关权利均受相应法律法规的保护。使用本项目应遵守相关法律法规和许可证的要求。
//  本项目主要遵循 MIT 许可证进行分发和使用。许可证位于源代码树根目录中的 LICENSE-MIT 文件。
//  不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目开发而产生的一切法律纠纷和责任，我们不承担任何责任！
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Mud.Feishu.AI.Tools.Extraction;
using Mud.Feishu.AI.Tools.Schema;

namespace Mud.Feishu.AI.Tools.Emit;

/// <summary>
/// Tier C 发射器：产出参数解包类型——每枚 <c>[FeishuTool]</c> 工具一个强类型入参类型
/// （<c>{Tool}Args</c>，独立产物文件），把执行器方法首部的 <c>ToolArgs.*(arguments, "…")</c>
/// 逐参读取收敛为<b>一次</b> <c>Unpack</c> 调用。
/// </summary>
/// <remarks>
/// <para>
/// <b>为什么值得生成</b>：参数名在「接口签名（C# 参数名 = <c>[ToolParameter]</c> 声明名）」与
/// 「执行器里的字符串字面量」两处独立维护，两者漂移的唯一表现是<b>运行期</b>
/// <c>ArgumentException: 缺少必填参数 x</c>——编译期零保证。生成 <c>Unpack</c> 后字段名由接口派生，
/// 改名即执行器编译失败（从运行期漂移降级为编译期错误）。
/// </para>
/// <para>
/// <b>归属与门槛</b>：产物消费 <c>Mud.Feishu.AI.FeishuTools</c> 的 <c>internal</c> 成员
/// （<c>ToolArgs</c>），故只发射进<see cref="SchemaEmitter.ToolNamesOwnerAssembly"/>——其他声明样例
/// <c>[FeishuTool]</c> 接口的工程（如 <c>Mud.Feishu.AI.Tests</c>）若一并发射会因 <c>ToolArgs</c>
/// 不可见而 <c>CS0103</c>。
/// </para>
/// <para>
/// <b>命名空间</b>：与 <c>ToolArgs</c> / <c>FeishuToolNames</c> 同属 <c>Mud.Feishu.AI.FeishuTools</c>
/// 根命名空间（执行器位于其下的 <c>.Internal</c>，经命名空间上溯直接可见，无 using 迁移）。
/// </para>
/// <para>
/// <b>不生成执行器方法体</b>：白名单投影、filter/sort 解析、RFC3339 转换、dry_run 摘要等业务逻辑
/// 仍由人写——生成器只搬运「从参数字典取值」这一机械动作。
/// </para>
/// </remarks>
internal static class ToolArgsEmitter
{
    /// <summary>产物目录名（每类型一个文件，hintName 前缀与 <c>FeishuToolNames.g.cs</c> 同体例分组）。</summary>
    public const string OutputFolder = "FeishuToolArgs";

    /// <summary>产物命名空间。</summary>
    public const string NamespaceName = "Mud.Feishu.AI.FeishuTools";

    /// <summary>类型名后缀（<c>bitable.list_tables</c> → <c>BitableListTablesArgs</c>）。</summary>
    public const string TypeSuffix = "Args";

    /// <summary>解包方法名。</summary>
    public const string UnpackMethodName = "Unpack";

    /// <summary>工具名常量名（契约守卫据此把类型映射回工具名，无需在测试里复刻 PascalCase 规则）。</summary>
    public const string ToolNameConstant = "ToolName";

    /// <summary>
    /// 发射参数解包产物（仅名字契约所有者程序集；无工具或不满足门槛时不产出）。
    /// 每枚 <c>{Tool}Args</c> 类型一个独立产物文件（<c>{OutputFolder}/{TypeName}.g.cs</c>）。
    /// </summary>
    /// <param name="context">源产出上下文。</param>
    /// <param name="models">Tier C 模型集合。</param>
    /// <param name="assemblyName">当前编译的程序集名（决定是否发射）。</param>
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<ToolSchemaModel> models,
        string? assemblyName)
    {
        if (models.IsEmpty
            || !string.Equals(assemblyName, SchemaEmitter.ToolNamesOwnerAssembly, StringComparison.Ordinal))
        {
            return;
        }

        foreach (var model in models.OrderBy(static m => m.Entry.ToolName, StringComparer.Ordinal))
        {
            // 不支持的参数形态已由 MUDFT020 上报（构建已失败），此处不产出半成品类型造成二次噪声。
            if (BuildPlan(context, model) is not { } plan)
            {
                continue;
            }

            context.AddSource(
                HintName(plan.TypeName),
                SourceText.From(RenderArgsType(plan), Encoding.UTF8));
        }
    }

    /// <summary>产物 hintName：每类型一个文件，按产物目录分组（<c>BitableListTablesArgs</c> → <c>FeishuToolArgs/BitableListTablesArgs.g.cs</c>）。</summary>
    public static string HintName(string typeName)
        => $"{OutputFolder}/{typeName}.g.cs";

    /// <summary>渲染单个 <c>{Tool}Args</c> 类型的完整产物源文件（文件头 + 命名空间 + 一个类型）。</summary>
    private static string RenderArgsType(ArgsPlan plan)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated> 由 FeishuToolSchemaGenerator 编译期产出，禁止手工修改 </auto-generated>");
        source.AppendLine("#nullable enable");
        source.AppendLine("#pragma warning disable CS1591 // 生成代码不逐一补 XML 注释");
        source.AppendLine($"namespace {NamespaceName}");
        source.AppendLine("{");
        WriteArgsType(source, plan);
        source.AppendLine("}");
        return source.ToString();
    }

    // ────────── 计划构造（唯一的上报点） ──────────

    /// <summary>把一枚工具的 <c>[ToolParameter]</c> 声明翻译为解包计划（含字段类型与读取表达式）。</summary>
    /// <returns>解包计划；含不可映射参数时返回 <see langword="null"/>（已上报 MUDFT020）。</returns>
    private static ArgsPlan? BuildPlan(SourceProductionContext context, ToolSchemaModel model)
    {
        var entry = model.Entry;
        var fields = new List<ArgsField>(entry.Parameters.Count);
        var unsupported = false;

        foreach (var parameter in entry.Parameters)
        {
            if (parameter.IsRequired && parameter.IsNullable)
            {
                // MUDFT021 上报点：Schema 会把它放进 required，而解包读的是必填读取器——
                // 该组合只在「[ToolParameter(Required=true)] 标注在可空参数上」时出现，属声明自相矛盾。
                Diagnostics.Report(context, Diagnostics.MUDFT021, null, entry.ToolName, parameter.Name);
            }

            if (!TryResolveReader(parameter, out var fieldType, out var reader))
            {
                // MUDFT020 上报点（扩展触发点）：新增参数类型时须先在 ToolArgs 补 helper 并登记映射。
                Diagnostics.Report(
                    context,
                    Diagnostics.MUDFT020,
                    null,
                    entry.ToolName,
                    parameter.Name,
                    parameter.CsharpType);
                unsupported = true;
                continue;
            }

            fields.Add(new ArgsField(
                name: parameter.Name,
                fieldName: SchemaEmitter.BuildNameConstant(parameter.Name),
                fieldType: fieldType,
                reader: reader,
                description: parameter.DocDescription));
        }

        return unsupported
            ? null
            : new ArgsPlan(
                toolName: entry.ToolName,
                typeName: SchemaEmitter.BuildNameConstant(entry.ToolName) + TypeSuffix,
                fields: fields);
    }

    /// <summary>
    /// 参数 → 解包读取器映射表（唯一真相源；与 <c>ToolArgs</c> 的 helper 集必须一一对应）。
    /// </summary>
    /// <remarks>
    /// <para>
    /// 只映射<b>当前工具面真实存在的形态</b>：<c>string</c> / <c>string?</c> / <c>string[]</c> /
    /// <c>string[]?</c> / <c>int?</c> / <c>bool?</c>（31 枚工具逐一核对）。
    /// </para>
    /// <para>
    /// <c>int</c> 必填与可选映射均提供（<c>RequireInt</c> / <c>OptionalInt</c>）；
    /// <c>bool</c> 仅提供可选映射（当前无工具声明必填布尔参数）。
    /// </para>
    /// </remarks>
    private static bool TryResolveReader(CapabilityParameter parameter, out string fieldType, out string reader)
    {
        var name = JsonText.ToCSharpLiteral(parameter.Name);
        var isRequired = parameter.IsRequired;

        switch (NormalizeTypeName(parameter.CsharpType))
        {
            case "string":
                if (isRequired)
                {
                    fieldType = "string";
                    reader = $"ToolArgs.RequireString(args, {name})";
                }
                else
                {
                    fieldType = "string?";
                    reader = $"ToolArgs.OptionalString(args, {name})";
                }

                return true;

            case "string[]":
                // 必填数组用 RequireStringArray（= OptionalStringArray + 缺失/为空即抛）——与 RequireString 同构。
                if (isRequired)
                {
                    fieldType = "string[]";
                    reader = $"ToolArgs.RequireStringArray(args, {name})";
                }
                else
                {
                    fieldType = "string[]?";
                    reader = $"ToolArgs.OptionalStringArray(args, {name})";
                }

                return true;

            case "int":
                if (isRequired)
                {
                    fieldType = "int";
                    reader = $"ToolArgs.RequireInt(args, {name})";
                }
                else
                {
                    fieldType = "int?";
                    reader = $"ToolArgs.OptionalInt(args, {name})";
                }

                return true;

            case "bool" when !isRequired:
                fieldType = "bool?";
                reader = $"ToolArgs.OptionalBool(args, {name})";
                return true;

            default:
                fieldType = string.Empty;
                reader = string.Empty;
                return false;
        }
    }

    /// <summary>
    /// 归一化 C# 类型显示名（去 <c>?</c>、别名与 CLR 名统一）——<c>ToDisplayString()</c> 的
    /// 可空引用注解与 <c>UseSpecialTypes</c> 选项跨版本有差异，按名匹配必须容错两侧写法。
    /// </summary>
    private static string NormalizeTypeName(string csharpType)
    {
        var name = csharpType.Trim().TrimEnd('?').Trim();
        return name switch
        {
            "System.String" or "String" => "string",
            "System.String[]" or "String[]" => "string[]",
            "System.Int32" or "Int32" => "int",
            "System.Boolean" or "Boolean" => "bool",
            _ => name,
        };
    }

    // ────────── 产物渲染 ──────────

    private static void WriteArgsType(StringBuilder source, ArgsPlan plan)
    {
        source.AppendLine($"    /// <summary>{XmlEscape(plan.ToolName)} 的模型入参（编译期从 [FeishuTool] / [ToolParameter] 声明派生）。</summary>");
        source.AppendLine($"    {GeneratedCodeMarker.Attribute}");
        source.AppendLine($"    internal sealed class {plan.TypeName}");
        source.AppendLine("    {");
        source.AppendLine($"        /// <summary>工具名契约常量（与 <c>FeishuToolNames</c> 同源；契约守卫据此把本类型映射回工具名）。</summary>");
        source.AppendLine($"        internal const string {ToolNameConstant} = {JsonText.ToCSharpLiteral(plan.ToolName)};");

        var locals = plan.Fields.Select(static f => LocalName(f.FieldName)).ToArray();

        if (plan.Fields.Count > 0)
        {
            source.AppendLine();
            source.AppendLine($"        {GeneratedCodeMarker.Attribute}");
            source.AppendLine($"        public {plan.TypeName}({string.Join(", ", plan.Fields.Select(static (f, i) => f.FieldType + " " + LocalName(f.FieldName)))})");
            source.AppendLine("        {");
            for (var i = 0; i < plan.Fields.Count; i++)
            {
                source.AppendLine($"            {plan.Fields[i].FieldName} = {locals[i]};");
            }

            source.AppendLine("        }");

            foreach (var field in plan.Fields)
            {
                source.AppendLine();
                if (!string.IsNullOrWhiteSpace(field.Description))
                {
                    source.AppendLine($"        /// <summary>{XmlEscape(field.Description!)}</summary>");
                }

                source.AppendLine($"        {GeneratedCodeMarker.Attribute}");
                source.AppendLine($"        public {field.FieldType} {field.FieldName} {{ get; }}");
            }
        }

        source.AppendLine();
        source.AppendLine("        /// <summary>从模型 tool_call 参数字典解包为强类型参数（与 [ToolParameter] 声明同源，编译期生成）。</summary>");
        source.AppendLine("        /// <exception cref=\"global::System.ArgumentException\">必填参数缺失或为空。</exception>");
        source.AppendLine($"        {GeneratedCodeMarker.Attribute}");
        source.AppendLine($"        public static {plan.TypeName} {UnpackMethodName}(global::System.Collections.Generic.IReadOnlyDictionary<string, object?> args)");
        source.AppendLine("        {");
        foreach (var field in plan.Fields)
        {
            source.AppendLine($"            var {LocalName(field.FieldName)} = {field.Reader};");
        }

        source.AppendLine(plan.Fields.Count == 0
            ? $"            return new {plan.TypeName}();"
            : $"            return new {plan.TypeName}({string.Join(", ", locals)});");
        source.AppendLine("        }");
        source.AppendLine("    }");
    }

    /// <summary>字段名 → 局部变量名（首字母小写；<c>AppToken</c> → <c>appToken</c>）。</summary>
    private static string LocalName(string fieldName)
        => char.ToLowerInvariant(fieldName[0]) + fieldName.Substring(1);

    /// <summary>XML 文档文本转义（参数说明含 <c>&amp;</c>/<c>&lt;</c>/<c>&gt;</c> 时不得破坏产物）。</summary>
    private static string XmlEscape(string text)
        => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    // ────────── 计划模型 ──────────

    /// <summary>一枚工具的解包计划。</summary>
    private sealed class ArgsPlan
    {
        public ArgsPlan(string toolName, string typeName, IReadOnlyList<ArgsField> fields)
        {
            ToolName = toolName;
            TypeName = typeName;
            Fields = fields;
        }

        public string ToolName { get; }

        public string TypeName { get; }

        public IReadOnlyList<ArgsField> Fields { get; }
    }

    /// <summary>一个参数的解包计划。</summary>
    private sealed class ArgsField
    {
        public ArgsField(string name, string fieldName, string fieldType, string reader, string? description)
        {
            Name = name;
            FieldName = fieldName;
            FieldType = fieldType;
            Reader = reader;
            Description = description;
        }

        /// <summary>模型可见参数名（snake_case）。</summary>
        public string Name { get; }

        /// <summary>PascalCase 字段名。</summary>
        public string FieldName { get; }

        /// <summary>字段类型（含可空标注）。</summary>
        public string FieldType { get; }

        /// <summary>解包读取表达式。</summary>
        public string Reader { get; }

        /// <summary>参数说明（XML <c>&lt;param&gt;</c> 或 <c>[ToolParameter]</c>）。</summary>
        public string? Description { get; }
    }
}
