<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Mud.Feishu.WebSocket.Demo</AssemblyName>
    <RootNamespace>Mud.Feishu.WebSocket.Demo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Test\**" />
    <Content Remove="Test\**" />
    <EmbeddedResource Remove="Test\**" />
    <None Remove="Test\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mud.Feishu.Abstractions" Version="3.0.0-preview2" />
    <PackageReference Include="Mud.Feishu.Redis" Version="3.0.0-preview2" />
    <PackageReference Include="Mud.Feishu.WebSocket" Version="3.0.0-preview2" />
    <PackageReference Include="Mud.Feishu.EventCallback" Version="3.0.0-preview2" />
  </ItemGroup>

  <!-- <ItemGroup>
    <ProjectReference Include="..\..\Mud.Feishu.Redis\Mud.Feishu.Redis.csproj" />
    <ProjectReference Include="..\..\Mud.Feishu.WebSocket\Mud.Feishu.WebSocket.csproj" />
	<ProjectReference Include="..\..\Mud.Feishu.EventCallback\Mud.Feishu.EventCallback.csproj" />
  </ItemGroup> -->

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>